### ISSUE TITLE
Improve USA seed scripts to support new Grade schema

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/openbeta-graphql#140]
Related #111 

The climb data seed script (loading USA data from JSON files to db) writes to field `YDS`.

https://github.com/OpenBeta/openbeta-graphql/blob/staging/src/db/import/ClimbTransformer.ts#L18

### To do:
- [ ] Use new grade field

**Comment by DarrenZLew** [comment]
Created PR https://github.com/OpenBeta/openbeta-graphql/pull/163 to start using the ~~grade~~ grades field

**Comment by vnugent** [comment]
@DarrenZLew is this done?

**Comment by DarrenZLew** [comment]
I believe so, yes.
