### ISSUE TITLE
Improve crag stats aggregation to support new grade schema

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/openbeta-graphql#141]
Related #111 

The statistics aggregate function uses `yds` field.   We need to migrate to the new grade schema..

https://github.com/OpenBeta/openbeta-graphql/blob/staging/src/db/utils/Aggregate.ts#L61

### Problem

How do we know which field to use? French/YDS?

**Comment by DarrenZLew** [comment]
In terms of the grading system, I think it would make the most sense to default to what is most commonly accepted for that crag/area/country. So for our current USA data and supporting grade types, this would be YDS and V-scale.

An example implementation would be https://www.thecrag.com/en/article/gradesonthecrag#article.gradesonthecrag.header.grade-contexts. They default to what is accepted at the country level, but this can be overwritten at individual crags/areas within the country.

**Comment by vnugent** [comment]
I created https://github.com/OpenBeta/openbeta-graphql/issues/157 to track this new grade context.

**Comment by DarrenZLew** [comment]
Created a PR to help update this: https://github.com/OpenBeta/openbeta-graphql/pull/163

Some additional work needed to update the statistics function to move some logic into sandbag
