### ISSUE TITLE
Create a separate job for updating country

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/openbeta-graphql#166]
Currently `yarn init-db` does 2 unrelated tasks: calculate crags statistics and seed the DB with all countries.  We should move the latter into its own job and make sure the the statistic job can run as often as needed.

https://github.com/OpenBeta/openbeta-graphql/blob/staging/src/db/utils/jobs/UpdateAllRunner.ts

**Comment by siman4457** [comment]
Is there anything left to do for this issue?

**Comment by vnugent** [comment]
It's done in PR #172.  Thanks for bringing it to my attention.
