### ISSUE TITLE
Use Date/timestamp for ticks

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/openbeta-graphql#175]
Tick date is currently stored as `YYYY-MM-DD` string.  We should store it in the db as Date or seconds from epoch to make it easier to  visualize/sort/filter

 https://github.com/OpenBeta/openbeta-graphql/blob/staging/src/db/TickTypes.ts#L8

**Comment by CocoisBuggy** [comment]
Hey Viet, I was thinking of integrating this with another PR I'm working on but there may be a bit of nuance:

When ticks are added to the database they are not of a guaranteed origin or shape. Most of the unstructured fields in the tick object come from trying to support both MP and OB native ticks. 

I have not looked too deeply into how the tick import system was made, but if the date climbed is a free text field on MP then it is not as simple as converting the field.

Someone will need to verify that MP ticks are structured in this way first, or we will need to perhaps support both date fields
