### ISSUE TITLE
Climb createdBy and createdAt not set

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/openbeta-graphql#218]
When I create new climbs on openbeta.io using the bulk editor, createdBy, createdAt, updatedBy are not set.

https://github.com/OpenBeta/openbeta-graphql/blob/develop/src/model/MutableClimbDataSource.ts#L140

---

<img width="490" alt="Screen Shot 2023-01-28 at 8 44 10 AM" src="https://user-images.githubusercontent.com/3805254/215254128-61287a0d-bfdc-406c-a5fa-7aa01d809848.png">

**Comment by CocoisBuggy** [comment]
I'll look into this, it looks like the code in the linked file should be sorted a little bit anyhow

**Comment by vnugent** [comment]
@CocoisBuggy 
It would be great if you can help fix this one!  While it's low impact it's highly visible as many users are now editing pages.  Thank you.

**Comment by vnugent** [comment]
I came across this issue while working on #273. It's actually a frontend bug - fixing it in https://github.com/OpenBeta/open-tacos/pull/800

**Comment by CocoisBuggy** [comment]
Excellent! I am a bit perplexed though. Shouldn't these fields should be inferred from auth context rather than simply being trusted as parameters given by the front end...?

**Comment by vnugent** [comment]
When a user performs an edit, the backend validates the user uuid and roles in the JWT token and correctly records it in the database.  This real cause behind this issue has to do with React code incorrectly displaying user uuid / username field.
