### ISSUE TITLE
Edit Readme to explain commit warnings.

### ISSUE THREAD

**Issue by bradleyDean** [OpenBeta/openbeta-graphql#262]
New contributors might waste time trying to resolve some warnings when comitting changes, which it turns out we are just ignoring for the time being.
When comitting changes, the following warnings appear:

```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.9.5

Please only submit bug reports when using the officially supported version.

=============
ts-standard: Typescript Standard Style! (https://github.com/standard/ts-standard)
ts-standard: Run `ts-standard --fix` to automatically fix some problems.

```

This issue proposes that we include some explanatory text in the readme that encourages contributors to ignore this warning for now.

If there is already a ticket about fixing the underlying conflict, we should probably link this issue to that one.

**Comment by musoke** [comment]
How hard is it to just fix the potential incompatibility?  This would make on-boarding smoother.
