### ISSUE TITLE
[Feature Request] Pagination support

### ISSUE THREAD

**Issue by gmkado** [OpenBeta/openbeta-graphql#304]
I'm new to graphql so apologies if this already exists.  Is there a way to page through the list of areas and request e.g. 10 areas at a time?  And would this result in faster query times from the server?  

Currently searching for a single letter takes ~10s and returns more results than I want to show to the user, ideally I wan the top 10 areas sorted by number of climbs.

**Comment by vnugent** [comment]
can you tell me which query/queries?

**Comment by gmkado** [comment]
Nevermind, I missed that you use typesense, which solves both issues.   I was using the playground and trying to query areas based on one-letter queries.
