### ISSUE TITLE
Run area aggregate (stats) updates only for an area and its ancestors

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/openbeta-graphql#319]
Frontend issue: https://github.com/OpenBeta/open-tacos/issues/877

### Background

- Currently, the only way to update area statistics is by manually running a Kubernetes job.  
- The job only updates USA tree
- Slow ~ 25 minutes

```bash
# The Kubernetes job calls
yarn update-stats
```
which calls https://github.com/OpenBeta/openbeta-graphql/blob/develop/src/db/utils/jobs/UpdateStatsJob.ts

### To do
Based on recent work for issue https://github.com/OpenBeta/openbeta-graphql/issues/213 we can introduce a similar function to only update the affected subtree

**Comment by siman4457** [comment]
I'll take a crack at this.

**Comment by siman4457** [comment]
Updating a climb's stats affects its parents.



## Potential Solution:
I don't think we have a way of referencing parent nodes. This can be fixed by adding a [reference to parent nodes](https://www.mongodb.com/docs/manual/tutorial/model-tree-structures-with-parent-references/):

```
{
  "_id": {
    "$oid": "6467ab2ae622317bdb3ef74c"
  },
  "area_name": "Indian Creek",
  "climbs": [],
  "children": [
    ...    
  ],
  "parent": ObjectId("<id of parent area/crag>"),
  ...
}
```
In this example, the parent would be the id of Southeast Utah since the pathTokens shows:

```
[
  0: "USA",
  1: "Utah",
  2: "Southeast Utah",
  3: "Indian Creek"
]
```

**Comment by vnugent** [comment]
`ancestors` is a CSV list of area ID's mirroring `pathTokens`

**Comment by siman4457** [comment]
Child:
```
_id: ObjectId("6467ab2ae622317bdb3ef74c")
area_name: "Indian Creek"
ancestors: "1db1e8ba-a40e-587c-88a4-64f5ea814b8e,ee1d37e7-dc41-5c26-a358-5d51af01f499,cbbfd7c6-5cf2-5063-8939-5f3233efa573,f166e672-4a52-56d3-94f1-14c876feb670"
pathTokens:[
  0: "USA",
  1: "Utah",
  2: "Southeast Utah",
  3: "Indian Creek"
]
```

Parent:
```
_id: ObjectId("6467ab2ae622317bdb3eef3f")
area_name: "Southeast Utah"
```

_id 6467ab2ae622317bdb3eef3f is not found in the ancestor list of the child. ~~Is there some conversion between the _id and strings saved in ancestors?~~

I see that a mmuid is being generated from paths in `genMUIDFromPaths()` in `src/model/MutableAreaDataSource.ts`. Seems like the mmuid generated is based on the area name and not the area id. 

```
const uuid = genMUIDFromPaths(parentPathTokens, areaName)
```

**Comment by vnugent** [comment]
For the Areas collection, `_id` is auto-generated by mongo.  I believe we're not using it anywhere.  What we use as the primary key is `metadata.area_id` (it's the uuid generated from `genMUIDFromPaths()`)

**Indian Creek**

ancestors: "1db1e8ba-a40e-587c-88a4-64f5ea814b8e,ee1d37e7-dc41-5c26-a358-5d51af01f499,**cbbfd7c6-5cf2-5063-8939-5f3233efa573**,f166e672-4a52-56d3-94f1-14c876feb670"

`cbbfd7c6-5cf2-5063-8939-5f3233efa573` is area_id of South East Utah

Looking it up in Mongo Express
  `{ metadata.area_id: UUID('cbbfd7c6-5cf2-5063-8939-5f3233efa573') }`

<img width="1094" alt="Screenshot 2023-06-20 at 4 57 07 PM" src="https://github.com/OpenBeta/openbeta-graphql/assets/3805254/4eae8f0a-4160-4673-b2b2-54b691335629">
