### ISSUE TITLE
Search too sensitive to dashes

### ISSUE THREAD

**Issue by musoke** [OpenBeta/openbeta-graphql#335]
I'm not sure if this issue belongs in https://github.com/OpenBeta/open-tacos/ or https://github.com/OpenBeta/openbeta-graphql/

## Steps to Reproduce

1. navigate to https://openbeta.io/
2. type "Kor Ingalls Route" in search box

## Current Behavior

No relevant results found
![image](https://github.com/OpenBeta/open-tacos/assets/16665084/e870a296-73b6-4b14-9332-b88adc13ca07)

## Expected Behavior

Results should be similar to searching for any of

"Kor-Ingalls Route"  (the exact name in the database)
![image](https://github.com/OpenBeta/open-tacos/assets/16665084/61552ed8-4890-4d55-b561-19077f2373cc)

"Kor(Ingalls Route" (it seems that other special characters don't affect results?)
![image](https://github.com/OpenBeta/open-tacos/assets/16665084/f57895a9-15a3-483d-a39e-43f65df62950)

"Kor0Ingalls Route" (putting digits in the query changes the search results, but the most useful is still at the top)
![image](https://github.com/OpenBeta/open-tacos/assets/16665084/225fae61-5c83-4f40-a8e0-59a704f4c8f1)

"KorIngalls Route"
![image](https://github.com/OpenBeta/open-tacos/assets/16665084/8d70eb7d-6403-41ec-81f0-bdcf78177d60)

## Browser & version
<---  Example: Firefox 102.7.0esr  -->

Firefox 114.0.2

**Comment by vnugent** [comment]
We host our search data on Typesense.   Maybe we need to define `token-separator` or `infix`?
https://typesense.org/docs/guide/tips-for-searching-common-types-of-data.html#model-numbers-part-numbers-skus

**Comment by musoke** [comment]
Yes, that should get us most of the way there.  I think it's more similar to the next example on that page: https://typesense.org/docs/guide/tips-for-searching-common-types-of-data.html#phone-numbers

**Comment by vnugent** [comment]
I deployed a fix and updated search indexes.  `kor ingalls` now returns Kors-Ingalls.

**Comment by musoke** [comment]
Looks good!
