### ISSUE TITLE
PR Build Pipeline broken

### ISSUE THREAD

**Issue by l4u532** [OpenBeta/openbeta-graphql#372]
@enapupe @vnugent 

Something apparently broke the PR build pipeline:
> Run docker/login-action@v2
> Error: Username and password required

See fx: https://github.com/OpenBeta/openbeta-graphql/actions/runs/7166351784/job/19510256065?pr=371

Might be related to https://github.com/OpenBeta/openbeta-graphql/commit/e43370c451c5d05370259980884f77837ed6a0ba

**Comment by enapupe** [comment]
That's strange, the last main branch build pushed to dockerhub without issues. Maybe someone changed credentials afterwards?
By the way, ideally we should not login to dockerhub if we are just building the container. 
I'm adding a patch to skip dockerhub login if it's a PR.

**Comment by vnugent** [comment]
It's failing because GitHub prevents contributors without write access to the repo to use/read secrets in PRs (Otherwise someone can submit a PR and print out secrets on the screen).

**Comment by vnugent** [comment]
Merged fix https://github.com/OpenBeta/openbeta-graphql/pull/373

@l4u532 can you please rebase your PR https://github.com/OpenBeta/openbeta-graphql/pull/371 and push again to verify the fix?
