### ISSUE TITLE
Renaming an area does not allow you to create another area with the same name

### ISSUE THREAD

**Issue by julianlam** [OpenBeta/openbeta-graphql#408]
Steps to reproduce:

1. Create an area `abc`
2. Rename it to `def`
3. Attempt to create a new area `abc`

Received error:

>  Unexpected error: E11000 duplicate key error collection: prod-openbeta.areas index: metadata.area_id_1 dup key: { metadata.area_id: UUID("6a4f8206-cea5-54a8-b5c3-a833520577c5") }

**Comment by julianlam** [comment]
Note: Editing an area to a once-used name seems to be fine.

**Comment by CocoisBuggy** [comment]
I think this may be linked to #409 It's a holdover from when we were frequently seeding data and didn't have many edit features for the actual data

**Comment by CocoisBuggy** [comment]
should be resolved by #410
