### ISSUE TITLE
Ticks should store the date in millis

### ISSUE THREAD

**Issue by Vichy97** [OpenBeta/openbeta-graphql#427]
When sorting ticks, we can't ensure they are in the correct order for a day. Two climbs on the same day are not necessarily ordered in the ticked-order because we only record the date as a string and don't have any additional time stamp. This isn't a huge deal and most users probably won't care, but millis are the standard way of recording time and how the rest of the api records timestamps.

**Comment by julianlam** [comment]
Having the end user specify time in addition to date may be little excessive. 

I'd _recommend_ making it optional. It's likely if the end user doesn't enter a time, they wouldn't care about the order being wrong.

**Comment by Vichy97** [comment]
We don't need the user to specify time. If the date is stored in millis, time can be implicitly captured.

**Comment by CocoisBuggy** [comment]
I'm gonna close the issue on this repo, but I'd strongly encourage you to open it on the open-tacos repo, which is where the date restriction is happening. Allowing users to optionally select a time should be quite straightforward.

Here is my reasoning, feel free to point out something I have missed

```ts
/**
 * Tick Schema
 *
 * The tick schema defines how ticks are stored and serialized in the mongo database.
 * see the TickTypes.ts file for the typescript interface that defines types as they
 * are used within the application. Getting documents from this schema should kick out
 * TickType objects.
 */
export const TickSchema = new Schema<TickType>({
  name: { type: Schema.Types.String, required: true, index: true },
  notes: { type: Schema.Types.String, required: false },
  climbId: { type: Schema.Types.String, required: true, index: true },
  userId: { type: Schema.Types.String, required: true, index: true },
  style: { type: Schema.Types.String, required: true, default: '' },
  attemptType: { type: Schema.Types.String, required: true, index: true, default: '' },
  dateClimbed: { type: Schema.Types.Date },
  grade: { type: Schema.Types.String, required: true, index: true },
  // Bear in mind that these enum types must be kept in sync with the TickSource enum
  source: { type: Schema.Types.String, enum: ['MP', 'OB'] as TickSource[], required: true, index: true }
})
```

The data type already supports date input to ms level precision. [more here](https://www.mongodb.com/docs/manual/reference/method/Date/).

the current tick creation method takes the data and doesn't truncate the date

```ts
async addTick (tick: TickInput): Promise<TickType> {
    return await this.tickModel.create({ ...tick })
  }
```

This is possibly its own issue... but that aside 

I did double check just for sanity's sake and I could put regular untruncated dates into the GQL mutation such that they would appear in the DB as they should be.

**Comment by Vichy97** [comment]
@CocoisBuggy it seems like this is still a bug for this repo then. The problem is probably both MP imports and openbeta.io not recording dates in millis. The former needs to be fixed in this repo right?

**Comment by CocoisBuggy** [comment]
@Vichy97 you might expect that to be the case but I dont think so... I wasn't involved with the tick import work, but as far as I can tell, the import actually happens by hitting a nextjs api route and then passing that data to the back end. 

(See open-tacos/src/app/api/user/bulkImportTicks/route.ts)

In that code the assumption seems to be that the MP data source will pass us a date with no time information - I don't see us doing any truncation but if there is a fix we can do I expect it is here.

I might be wrong about all this, I haven't delved much into the ticks

**Comment by Vichy97** [comment]
@CocoisBuggy I know MP doesn't contain time information, but that doesn't prevent us from converting their timestamp into millis. We aren't converting to millis, but I think we should do so

**Comment by CocoisBuggy** [comment]
@Vichy97  It's possible I don't understand your meaning. The time is necesarily encoded to millisecond accuracy by the time it hits the database, and in any event upsampling wouldn't improve sorting.

Because we get a date from MP we expand that to <date> 00:00.000 (because a time is unknown).

So, if I understand what you're saying, we are recording it with millisecond precision already

**Comment by Vichy97** [comment]
I'm a bit confused, but what I'm asking for is for the API to stop returning a String for dates, it should return a Long (millis). I'm not concerned with extracting an exact timestamp from MP, just that the API should return whatever date MP gives us as a Long instead of a String

**Comment by vnugent** [comment]
@Vichy97 which queries?  I believe they're already returning milliseconds.

**Comment by Vichy97** [comment]
> @Vichy97 which queries?  I believe they're already returning milliseconds.

Querying ticks by user id has the dateClimbed as a string

**Comment by vnugent** [comment]
both queries return **dateClimbed** as number

<img width="525" alt="Screenshot 2024-12-01 at 6 34 15 PM" src="https://github.com/user-attachments/assets/7c3fc0af-ef21-404b-ab8d-c2737bcd1464">
<img width="556" alt="Screenshot 2024-12-01 at 6 34 54 PM" src="https://github.com/user-attachments/assets/86cffa52-2dc2-4c33-97c0-bebbd6517689">
