### ISSUE TITLE
Add getPhotos query

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/openbeta-graphql#74]
Add a new query to help getting photo URLs by bounding box or area id/climb id.

**Comment by admanny** [comment]
Hi @vnugent, would like to take this on if it's still needed. Thanks

**Comment by vnugent** [comment]
This has been done in #78. Sorry it's my bad not updating the issue.  
Can you help me with these two?

1. https://github.com/OpenBeta/openbeta-graphql/issues/90 (instead of console.log)
2. https://github.com/OpenBeta/openbeta-graphql/issues/83 (email viet at openbeta.io for typesense api key)

**Comment by admanny** [comment]
Absolutely, will work on them. Thank you
