### ISSUE TITLE
Create an area index on Typesense

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/openbeta-graphql#83]
Create a search index on Typesense containing only area data including climb count, density

**Comment by CocoisBuggy** [comment]
I've got related issues assigned elsewhere getting blocked by this, so I'll take this one on

**Comment by vnugent** [comment]
Additional tasks:

- [x] Create a separate CLI job.  See https://github.com/OpenBeta/openbeta-graphql/blob/staging/package.json#L58
   Please don't piggyback this job with the existing climbs job in Typesense.tsx since we want to be able to re-build areas index as needed without impacting the other job.
- [x] Create a new Kubernetes job in dev-ops project (TBD: Viet)
