### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/openbeta-graphql#93]
The readme is lacking set up instructions for seeding the database with test data.

**Comment by Ali7040** [comment]
can I work on this issue?

**Comment by melissapthai** [comment]
I was able to successfully seed the database with test data from the current readme instructions, however I did have to install wget on my machine to get the seed-db script to work. Happy to update the instructions to reflect this, if no one else is doing it!

**Comment by vnugent** [comment]
@melissapthai yes please.
